Feature/architecture
Olderestin/coin-flip-telegram-bot pull request #1
Opened 2024-01-27 16:03 UTC by Olderestin

## What changed?     
     
## Checklist before requesting a review     
- [ ] I have performed a self-review of my code  
- [ ] I have changed architectury of project
- [ ] Update Docker container build
- [ ] Make docstrings
- [ ] Add Poetry to the project
- [ ] Code is functional on my machine(Windows 10/Debian GNU/Linux 11 (bullseye))

2024-01-27 18:16 UTC, DmitroPodolsky requested changes
Need changes!

2024-01-27 18:16 UTC, memhard commented on .gitignore
> +user.db
consider the possibility ignore all files in storage root

2024-01-27 18:16 UTC, memhard commented on bot/__main__.py
> +logger.add("storage/app.log", rotation="500 MB", level="TRACE")
consider the possibility of using Pathlib variable, not a string just

2024-01-27 18:16 UTC, memhard commented on bot/db.py
> +    """
why describe variables in the class description?

2024-01-27 18:16 UTC, memhard commented on bot/db.py
> +        """
unnecessary information

2024-01-27 18:16 UTC, memhard commented on bot/db.py
> +        """
where annotation + outdated docs

2024-01-27 18:16 UTC, memhard commented on bot/db.py
> +        self.conn = sqlite3.connect(self.db_path / "user.db")
consider the possibility less use connections to the database

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>          try:
consider the possibility the closing cursors, not connections

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def make_flip(self, user_id: int):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def add_user(self, user_id: int):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def create_user_table(self):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def __exit__(self, exc_type, exc_val, exc_tb):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def __enter__(self):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on bot/db.py
>      def __init__(self, db_path: Path = settings.DATABASE_URL):
where annotation

2024-01-27 18:16 UTC, DmitroPodolsky commented on dockerfile
> +COPY . /app/bot
COPY . /app/bot must be place almost at the very end of the process

2024-01-27 18:16 UTC, DmitroPodolsky commented on dockerfile
> +COPY . /app/bot
why not just bot dir? not /app/bot

2024-01-27 18:16 UTC, DmitroPodolsky commented on README.md
> +- logs foler `bot/storage`
folder?

2024-01-27 19:33 UTC, Olderestin commented on README.md
> +- logs foler `bot/storage`
Yes

2024-01-27 19:35 UTC, Olderestin commented on bot/db.py
> +        """
I have to describe what contains in result parameter?

2024-01-27 19:44 UTC, Olderestin commented on bot/db.py
> +    """
I have seen such description in fastapi_users library, so i thought to do it like this. As i understand, I have to describe variables in __init__

2024-01-28 02:11 UTC, Olderestin reviewed
Task done.

2024-01-28 14:16 UTC, DmitroPodolsky reviewed
LGTM 👍 but still need some changes

2024-01-28 14:16 UTC, memhard commented on bot/config.py
> +USER_BD: UserDatabase = UserDatabase(settings.DATABASE_PATH)
what is BD? why we use annotation there?

2024-01-28 14:16 UTC, memhard commented on bot/db.py
> +    def __enter__(self) -> UserDatabase:
it's doesn't return UserDatabase object + bad docstring

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/db.py
> +        """
consider the possibilty to remake docstring, like example:
```bash
"""
Simulates a coin flip, updates user statistics.

Args:
      param user_id: The ID of the user making the flip.
Returns:
      some result(example)
 """
````

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/db.py
> +        """
same

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/handlers.py
> +    """
same

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/handlers.py
> +    """
same

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/handlers.py
> +    """
same

2024-01-28 14:16 UTC, DmitroPodolsky commented on bot/handlers.py
> +    """
same

2024-01-28 17:41 UTC, Olderestin reviewed
Changes done.

2024-01-28 18:02 UTC, DmitroPodolsky approved these changes
LGTM 👍 can approve to the dev branch

2024-01-28 18:02 UTC, memhard commented on bot/db.py
> +    def get_stats(self, user_id: int) -> Tuple[int, int, int]:
consider the possibility don't using typing, we can just use tuple(python 3.11)

2024-01-29 13:22 UTC, merged